<?php

// Create flags directory if it doesn't exist
if (!file_exists('assets/flags')) {
    mkdir('assets/flags', 0777, true);
}

// Flag images in base64
$flags = [
    'en' => 'iVBORw0KGgoAAAANSUhEUgAAABAAAAALCAMAAABBPP0LAAAAG1BMVEUdm/8Aa/89h/8Bed/f7/+/v/8/P/8/P/+/v7/KIzUVAAAAOklEQVR4AY3LQREAMAgDsWb/l5tDBJ4vkAAhIwDhBAiBMAKhMIJQGEEojCCE4QSBEJxAKIwgFEYQCiMAX4Y3Z75PPsEAAAAASUVORK5CYII=',
    'hi' => 'iVBORw0KGgoAAAANSUhEUgAAABAAAAALCAMAAACBPP0LAAAAnFBMVEX/mTMA/0YA/4YAgFYAhFYA/4YA/4YA/4YA/4YA/4YA/4YA/4YA/4YA/4YA/4YA/4YA/4YA/4YA/4YA/4YA/4YA/4YA/4YA/4YA/4YA/4YA/4YA/4YA/4YA/4YA/4YA/4YA/4YA/4YA/4YA/4YA/4YA/4YA/4YA/4YA/4YA/4YA/4YA/4YA/4YA/4YA/4YA/4YA/4YA/4YA/4YA/4YA/4aQ6E7HAAAANHRSTlMAAAECAwQFBgcICQoLDA0ODxAREhMUFRYXGBkaGxwdHh8gISIjJCUmJygpKissLS4vMDEyJ8V0/QAAAE5JREFUeF5VyEcSgDAMBMEVOeecczD//zccwGOvNTPrwQhGMIIRjGAEIxjBCEYwghGMYAQjGMEIRjCCEYxgBCMYwQhGMIIRjGAEI/wAzHEF4yUf5JAAAAAASUVORK5CYII=',
    'pa' => 'iVBORw0KGgoAAAANSUhEUgAAABAAAAALCAMAAABBPP0LAAAAXVBMVEUAZs0AZs0AZs0AZs0AZs0AZs0AZs0AZs0AZs0AZs0AZs0AZs0AZs0AZs0AZs0AZs0AZs0AZs0AZs0AZs0AZs0AZs0AZs0AZs0AZs0AZs0AZs0AZs0AZs0AZs0AZs2l8j/RAAAAH3RSTlMAAAECAwQFBgcICQoLDA0ODxAREhMUFRYXGBkaGxwdHqRz9QAAAEJJREFUeF5VyEcOgDAMBMEFQui9hvz/nxjBh73WzKwHIxjBCEYwghGMYAQjGMEIRjCCEYxgBCMYwQhGMIIRjGAEI/wAJ2YF49t8qyQAAAAASUVORK5CYII='
];

// Save each flag
foreach ($flags as $code => $base64) {
    $file = "assets/flags/{$code}.png";
    file_put_contents($file, base64_decode($base64));
    echo "Created {$file}\n";
}

echo "All flags created successfully!\n";
?> 